web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import confirm_email
from django.contrib.auth import logout
from django.shortcuts import redirect
from exercises.api.api import UserSolvedProblemlist, UserSolvedProblemlistDetail
def logout_view(request):
    # 추가적인 로그아웃 전처리 작업이 있다면 여기에 추가

    logout(request)
    return redirect('/')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls'), name='main'),
    path('exercises/', include('exercises.urls'), name='exercises'),
    path('logout/', logout_view, name='logout'),
    path('api/solved_list/', UserSolvedProblemlist.as_view(), name='problem_list'),
    path('api/solved_list/<str:username>/', UserSolvedProblemlistDetail.as_view(), name='problem_list'),
]

web/exercises/urls.py
from django.urls import path
from exercises import views

app_name = 'exercises'

urlpatterns = [
    path('', views.home, name='home'),
    path('problem_type/', views.problem_type, name='problem_type'),
    path('editor/', views.editor, name='editor'),
    path('share/', views.share, name='share'),
    path('grade/', views.grade, name='grade'),
    path('share_grade/', views.share_grade, name='share_grade'),
    path('test/', views.test_page, name='test'),
    path('about/', views.about_us, name='about'),
    path('login/', views.login, name = 'login'),
    path('mypage/', views.mypage, name='exercises'),
]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from allauth.account.views import confirm_email

urlpatterns = [
    path('', views.home),
    path('login/', views.login, name = 'login'),
]

web/exercises/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserSolvedProblems(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    problems = models.CharField(max_length=255)
    solved = models.IntegerField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.problems:
            self.problems = '0'
        if not self.solved:
            self.solved = 0

    def __str__(self):
        return f"User: {self.user.username}, Problems: {self.problems}, Solved: {self.solved}"


@receiver(post_save, sender=User)
def create_user_solved_problems(sender, instance, created, **kwargs):
    if created:
        UserSolvedProblems.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_solved_problems(sender, instance, **kwargs):
    instance.usersolvedproblems.save()

web/exercises/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt
from exercises.api import api
import json
import base64
from rest_framework import generics
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount
import requests
import matplotlib.pyplot as plt
import matplotlib
from requests.exceptions import RequestException
from django.contrib.auth.models import User
from .models import UserSolvedProblems

# Create your views here.
# home
def home(request):
    if request.method == 'POST':
        keyword_list = ['print', 'input', 'for', 'if', 'math']

        # generate a problem with keywords
        problem = api.create_problem_sentence(keyword_list, False)

        # encode the problem
        problem_b64 = base64.b64encode(problem.encode('ascii')).decode('ascii')
        return redirect(reverse('exercises:editor') + '?p=' + problem_b64 + '&chat=false')

    return render(request, 'exercises/home.html')


#problem type
def problem_type(request):
    """exercises home page view

        Args:
            request (request): django request

        """
    # post
    if request.method == 'POST':
        keyword_list = request.POST.getlist('keyword_list')

        # generate a problem with keywords
        problem = api.create_problem_sentence(keyword_list, True)

        # encode the problem
        problem_b64 = base64.b64encode(problem.encode('ascii')).decode('ascii')
        keywords = ''
        for keyword in keyword_list:
            keywords += '&keyword=' + keyword
        return redirect(reverse('exercises:editor') + '?p=' + problem_b64 + '&chat=true' + keywords)

    return render(request, 'exercises/problem_type.html')


#editor
@ensure_csrf_cookie
def editor(request):
    """exercises editor page view

    Args:
        request (request): django request
        problem_id (string): base64 encoded problem

    """
    # post
    if request.method == 'POST':
        # data from user
        data = json.loads(request.body)

        if data['type'] == 'run':

            # compile the code
            compile_output = api.compile_code(data['source_code'], data['stdin'])

            # response
            response_data = {
                'status':'ok',
                'stdout':'',
                'compile_output': compile_output,
                'time':'0',
                'memory':'0'
            }

            return JsonResponse(response_data)

    # get
    if request.method == 'GET':
        problem = request.GET.get('p', None)
        b64_p = problem

        # decode problem
        problem = base64.b64decode(problem).decode('ascii')

        is_chat = request.GET.get('chat')
        keywords = ''
        if is_chat:
            keyword_list = request.GET.getlist('keyword')
            for keyword in keyword_list:
                keywords += keyword + ','

        # generate example code and result
        ex_code = api.generate_code(problem)
        ex_result = api.compile_code(ex_code, '1\r\n2\r\n3\r\n4')

        context = {'problem': problem, 'ex_result': ex_result, 'ex_code': ex_code, 'base64_problem': b64_p,
                   'is_chat': is_chat, 'keywords': keywords[:-1]}
        return render(request, 'exercises/editor.html', context)


@csrf_exempt
def share(request):
    """exercises editor share page view

    Args:
        request (request): django request
        problem_id (string): base64 encoded problem

    """
    # post
    if request.method == 'POST':
        # data from user
        data = json.loads(request.body)

        # compile the code
        compile_output = api.compile_code(data['source_code'], data['stdin'])

        # response
        response_data = {
            'status':'ok',
            'stdout':'',
            'compile_output': compile_output,
            'time':'0',
            'memory':'0'
        }

        return JsonResponse(response_data)

    # get
    if request.method == 'GET':
        problem = request.GET.get('p', None)
        b64_p = problem

        # decode problem
        problem = base64.b64decode(problem).decode('ascii')

        # generate example code and result
        ex_code = api.generate_code(problem)
        ex_result = api.compile_code(ex_code, '1\r\n2\r\n3\r\n4')

        context = {'problem': problem, 'ex_result': ex_result, 'ex_code': ex_code, 'base64_problem': b64_p}
        return render(request, 'exercises/share_editor.html', context)


@ensure_csrf_cookie
def grade(request):
    if request.method == 'POST':
        problem = request.POST.get('problem')
        user_code = request.POST.get('user-code')
        answer_code = request.POST.get('ex-code')
        grade_result = api.grade_code(problem, user_code, answer_code)
        username = request.user.username
        is_chat = request.POST.get('is-chat')
        keywords = request.POST.get('keywords').split(',')

        context = {'pass': grade_result['pass'], 'score': grade_result['score'], 'reason': grade_result['reason'],
                   'answer_code': answer_code, 'is_chat': is_chat, 'keywords': keywords}
        
                # UserSolvedProblems 모델 인스턴스 가져오기
        try:
            user_solved_problems = UserSolvedProblems.objects.get(user__username=username)
        except UserSolvedProblems.DoesNotExist:
            # 사용자에 대한 UserSolvedProblems 인스턴스가 없는 경우, 생성
            user = User.objects.get(username=username)
            user_solved_problems = UserSolvedProblems.objects.create(user=user)

        if grade_result['pass'] == True:
            # problems 필드 값 1 증가
            user_solved_problems.problems = str(int(user_solved_problems.problems) + 1)

            # solved 필드 값 1 증가
            user_solved_problems.solved += 1
            user_solved_problems.save()
        else:
            # problems 필드 값 1 증가
            user_solved_problems.problems = str(int(user_solved_problems.problems) + 1)
            user_solved_problems.save()
        return render(request, 'exercises/grade.html', context)


@csrf_exempt
def share_grade(request):
    if request.method == 'POST':
        problem = request.POST.get('problem')
        user_code = request.POST.get('user-code')
        answer_code = request.POST.get('ex-code')
        grade_result = api.grade_code(problem, user_code, answer_code)

        context = {'pass': grade_result['pass'], 'score': grade_result['score'], 'reason': grade_result['reason'],
                   'answer_code': answer_code}
        return render(request, 'exercises/share_grade.html', context)


def test_page(request):
    return render(request, 'exercises/test_page.html')


def about_us(request):
    return render(request, 'exercises/about_us.html')


def login(request):
    
    return render(request, 'exercises/login.html')

def mypage(request):
    matplotlib.use('Agg')
    # API에서 데이터 가져오기
    username = request.user.username
    print(username)
    url = 'http://127.0.0.1:8000/api/solved_list/'+ username+ '/'
    response = requests.get(url)
    data = response.json()
    print(data)
    # 데이터 가공
    if data:
        problems = int(data['problems'])  # 정수로 변환
        solved = int(data['solved'])  # 정수로 변환
        if problems == 0:
            success_rate = 0
        else:
            success_rate = solved / problems * 100  # 정답률 계산
    else:
        problems = 0
        solved = 0

    # 파이 차트 생성
    labels = ['Solved', 'Unsolved']
    sizes = [int(solved), int(problems) - int(solved)]
    colors = ['#E0708C', '#70B3E0']  # 멋진 색상으로 변경
    textprops = {'fontsize': 12, 'color': 'white', 'fontweight': 'bold'}  # 텍스트 스타일 변경
    explode = [0.05, 0]  # 조각 분리

    plt.figure(figsize=(8, 6))  # 차트의 크기 조정

    # 파이 차트
    plt.subplot(2, 2, 1)  # 그리드에 위치 설정
    plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=90,
            explode=explode, textprops=textprops, shadow=True)  # 디자인 요소 적용
    plt.axis('equal')
    plt.title('Problem Status')


    # 차트 이미지를 저장
    chart_image_path = 'static/chart.png'
    plt.tight_layout()  # 차트 간격 조정
    plt.savefig(chart_image_path)

    # 템플릿에 전달할 context 설정
    context = {
        'chart_image_path': chart_image_path,
        'problems': problems,
        'solved': solved,
        'success_rate': success_rate,
    }
    
    return render(request, 'exercises/mypage.html', context)




class my_social:
    def get_current_user_uid(request):
        if request.user.is_authenticated:
            try:
                social_account = SocialAccount.objects.get(user=request.user)
                uid = social_account.uid
                return uid
            except SocialAccount.DoesNotExist:
                pass
        return None

web/templates/exercises/about_us.html
{% extends 'base.html' %}
{% block content %}

<div class="about-us-container">
    <div class="about-us-main">
        <div class="about-us-main-text">
            <p class="about-us-main-text1">About us</p>
            <p class="about-us-main-text2">Let me introduce the development team</p>
        </div>
    </div>
    <div class="person-information1">
        <img src="/static/img/person-icon.png" width="200px" height="200px">
        <div class="person-information1-text">
            Name : 
            <br>
            Department of Software Engineering         
            <br>
            Student Id : 
            <br>
            Email : 
            <br>
            
        </div>
    </div>
    <hr>
    <div class="person-information2">
        <div class="person-information2-text">
            Name : Ji Won Seo
            <br>
            Department of Software Engineering         
            <br>
            Student Id : 201835465
            <br>
            Email : jwjw9964@gachon.ac.kr
            <br>
        </div>
        <img src="/static/img/person-icon.png" width="200px" height="200px">
    </div>
    <hr>
    <div class="person-information3">
        <img src="/static/img/person-icon.png" width="200px" height="200px">
        <div class="person-information3-text">
            Name : 
            <br>
            Department of Software Engineering         
            <br>
            Student Id : 
            <br>
            Email : 
            <br>
        </div>
    </div>
</div>

{% endblock %}

web/templates/exercises/editor.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">
    <!-- jQuery JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/golden-layout/1.5.9/goldenlayout.min.js" integrity="sha256-NhJAZDfGgv4PiB+GVlSrPdh3uc75XXYSM4su8hgTchI=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/golden-layout/1.5.9/css/goldenlayout-base.css" integrity="sha256-oIDR18yKFZtfjCJfDsJYpTBv1S9QmxYopeqw2dO96xM=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/golden-layout/1.5.9/css/goldenlayout-dark-theme.css" integrity="sha256-ygw8PvSDJJUGLf6Q9KIQsYR3mOmiQNlDaxMLDOx9xL0=" crossorigin="anonymous" />

    <script>
        var require = {
            paths: {
                "vs": "https://unpkg.com/monaco-editor/min/vs",
                "monaco-vim": "https://unpkg.com/monaco-vim/dist/monaco-vim",
                "monaco-emacs": "https://unpkg.com/monaco-emacs/dist/monaco-emacs"
            }
        };

        function share(){
            var problem = "{{base64_problem}}"
            prompt('msg','<iframe width="800" height="800" src="http://127.0.0.1:8000/exercises/share/?p=' + problem + '">');
        };

    </script>
    <script src="https://unpkg.com/monaco-editor/min/vs/loader.js"></script>
    <script src="https://unpkg.com/monaco-editor@0.32.1/min/vs/editor/editor.main.nls.js"></script>
    <script src="https://unpkg.com/monaco-editor@0.32.1/min/vs/editor/editor.main.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI=" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/download.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/ide.js' %}"></script>

    <link type="text/css" rel="stylesheet" href="{% static 'css/ide.css' %}">

    <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
    <title>CoFriend</title>
</head>
<body>

<!-- 페이지 내용 -->
<div class = "problem-container">
    <div class="problem">
        <div class="problem-1">Problem</div>
        <div class="problem-2">
           {{problem}}
        </div>
    </div>
    <div class="ex-result">
        <div class="ex-result-1">Example result</div>
        <div class="ex-result-2">
            {{ex_result}}
        </div>
    </div>
</div>
    <div id="site-navigation" class="ui small inverted menu">
        <div class="left menu">
            <div class="ui dropdown item site-links on-hover">
                File <i class="dropdown icon"></i>
                <div class="menu">
                    <div class="item" onclick="downloadSource()"><i class="download icon"></i> Download</div>
                </div>
            </div>
            <div class="item borderless">
                <select id="select-language" class="ui dropdown">
                    <option value="71" mode="python">Python (3.8.1)</option>
                </select>
            </div>
            <div class="item borderless wide screen only">
                <div class="ui input">
                    <input id="command-line-arguments" type="text" placeholder="Command line arguments"></input>
                </div>
            </div>
            <div class="item no-left-padding borderless">
                <button id="run-btn" class="ui primary labeled icon button"><i class="play icon"></i>Run (F9)</button>
            </div>
            <div class="item no-left-padding borderless">
                <button id="share-btn" class="ui primary labeled icon button" onclick="share()">Share</button>
            </div>
            <form class="item no-left-padding borderless" action="{% url 'exercises:grade' %}" method="post">
                {% csrf_token %}
                <input type="text" name="problem" style="display: none" value="{{problem}}">
                <textarea id="user-code" style="display: none" name="user-code" value=""></textarea>
                <textarea id="ex-code" style="display: none" name="ex-code">{{ex_code}}</textarea>
                <input type="text" id="is-chat" style="display: none" name="is-chat" value="{{is_chat}}">
                <input type="text" id="keywords" style="display: none" name="keywords" value="{{keywords}}">
                <input type="submit" class="ui primary labeled icon button" value="Grade">
            </form>
            <div id="navigation-message" class="item borderless">
                <span class="navigation-message-text"></span>
            </div>
        </div>
    </div>

    <div id="site-content"></div>

    <div id="site-modal" class="ui modal">
        <div class="header">
            <i class="close icon"></i>
            <span id="title"></span>
        </div>
        <div class="scrolling content"></div>
        <div class="actions">
            <div class="ui small labeled icon cancel button">
                <i class="remove icon"></i>
                Close (ESC)
            </div>
        </div>
    </div>

    <div id="site-settings" class="ui modal">
        <i class="close icon"></i>
        <div class="header">
            <i class="cog icon"></i>
            Settings
        </div>
        <div class="content">
            <div class="ui form">
                <div class="inline fields">
                    <label>Editor Mode</label>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="editor-mode" value="normal" checked="checked">
                            <label>Normal</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="editor-mode" value="vim">
                            <label>Vim</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="editor-mode" value="emacs">
                            <label>Emacs</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="site-footer">
        <div id="editor-status-line"></div>
        <span>© 2016-2022 <a href="https://judge0.com?ref=ide">Judge0</a>
        <span id="status-line"></span>
    </div>

<footer class="footer-bar">
    <div>
        <h2 class="text-uppercase">Team Co-Friend</h2> <br/>
            <p>Team Leader : Kim Won Jong | Business License : 000-00-0000</p>
            <p>Address : Gachon University \ CS : +82 (0)0-000-0000, Fax : +82 (0)0-000-0000</p>
        </div>

    <div>
        <div> Copyright ⓒ Team Co-Friend</div>
    </div>
</footer>
</body>
</html>

web/templates/exercises/grade.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}

{% block content %}
<div class="grade-main">
        <div class="grade-main-text">
            <p class="grade-main-text1">Result of the grading</p>
        </div>
</div>
<div class="grade-info">
    <p class="result-1">Result</p>
    <p class="result-2">{{pass}}</p>
    <p class="score-1">Score</p>
    <p class="score-2">{{score}}</p>
    <p class="result-reason-1">Result Reason</p>
    <p class="result-reason-2">{{reason}}</p>
    <p class="answer-code-1"> Answer code </p>
    <pre class = "answer-code-2">{{answer_code}}</pre>
</div>
{% if is_chat == 'true' %}
<form action="{% url 'exercises:problem_type' %}" method="post">
    {% csrf_token %}
    {% for keyword in keywords %}
    <input type="checkbox" name="keyword_list" style="display: none" value="{{keyword}}" checked>
    {% endfor %}
    <input type="button" class="btn btn-outline-primary" value="Repeat" onClick="history.go(-1)">
    &nbsp &nbsp &nbsp &nbsp
    <form action="{% url 'exercises:home' %}" method="get">
        <input type="submit" class="btn btn-outline-primary"  value="Go to Choose Problem Page">
    </form>
    &nbsp &nbsp &nbsp &nbsp
    <input type="submit"  class="btn btn-outline-primary"  value="Next Problem">
</form>
{% else %}
<form action="{% url 'exercises:home' %}" method="post">
    {% csrf_token %}
    <div class="grade-buttons">
        <input type="button" class="btn btn-outline-primary" value="Repeat" onClick="history.go(-1)">
        &nbsp &nbsp &nbsp &nbsp
        <form action="{% url 'exercises:home' %}" method="get">
            <input type="submit" class="btn btn-outline-primary"  value="Go to Choose Problem Page">
        </form>
        &nbsp &nbsp &nbsp &nbsp
        <input type="submit" class="btn btn-outline-primary"  value="Next Problem">
    </div>
</form>
{% endif %}
{% endblock %}

web/templates/exercises/home.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}

{% block content %}
<div class=" exercise-home-container">
    <div class = "exercise-home-main">
        <div class="exercise-home-text">
            <p class="exercise-home-text1">Exercise</p>
            <p class="exercise-home-text2">exercise</p>
        </div>
    </div>
    <div class = "exercise-home-choose">
        <div class = "random-button">
            <img src="/static/img/random-problem-icon.png" alt="random problem" width="150px" height="100px">
            <span style="margin-top: 50px"></span>
            <form action="{% url 'exercises:home' %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-outline-primary random_problem" value="random problem">
            </form>
        </div>
        <div class='v-line'></div>
        <div class = "chatgpt-button">
            <img src="/static/img/chatgpt-icon.png" alt="random problem" width="150px" height="100px">
            <span style="margin-top: 50px"></span>
            <form action="{% url 'exercises:problem_type' %}" method="get">
                <input type="submit" class="btn btn-outline-primary chatgpt_problem" value="chat-gpt problem">
            </form>
        </div>
    </div>
</div>
{% endblock %}

web/templates/exercises/login.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}

{% block content %}

{% load static %}
{% load socialaccount %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css">
<style>
    .btn-social-login {
        transition: all .2s;
        outline: 0;
        border: 1px solid transparent;
        padding: .5rem !important;
        border-radius: 50%;
        color: #fff;
    }

    .btn-social-login:focus {
        box-shadow: 0 0 0 .2rem rgba(0, 123, 255, .25);
    }

    .text-dark {
        color: #343a40 !important;
    }
</style>

<div class="login-main">
    <div class="login-wrapper">
        <h2>Login</h2>
        <form method="post" action="서버의url" id="login-form">
            <input type="text" name="userName" placeholder="Email">
            <input type="password" name="userPassword" placeholder="Password">
            <input type="submit" value="Login">
        </form>
    </div>
    <div class="login-social">
        <a href="{% provider_login_url 'google' method='oauth2' %}"><button class='btn-social-login' style='background:#D93025'><i class="xi-3x xi-google"></i></button></a>
        <a href="{% provider_login_url 'facebook' method='oauth2' %}"><button class='btn-social-login' style='background:#4267B2'><i class="xi-3x xi-facebook"></i></button></a>
        <a href="{% provider_login_url 'naver' method='oauth2' %}"><button class='btn-social-login' style='background:#1FC700'><i class="xi-3x xi-naver"></i></button></a>
        <a href="{% provider_login_url 'kakao' method='oauth2' %}"><button class='btn-social-login' style='background:#FFEB00'><i class="xi-3x xi-kakaotalk text-dark"></i></button></a>
    </div>
</div>
{% endblock %}

web/templates/exercises/mypage.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}

{% block content %}
<div class = "my-page-container">
    <div class="my-page-main">
        <div class="my-page-text">
            <p class="my-page-text1">My Page</p>
            <p class="my-page-text2">Check your coding learning status</p>
        </div>
    </div>
    <div class="my-page-container2">
        <div class="my-page-result">
            <div class="my-page-chart">
                {% load static %}
                <img src="{% static 'chart1.png' %}" alt="Problem Status Chart">
            </div>
            <div class="my-page-info">
                <h1> Number of Questions: {{ problems }}</h1>
                <br>
                <h1> Solved Questions: {{ solved }}</h1>
                <br>
                <h1> Wrong Questions:  </h1>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/templates/exercises/problem_type.html
{% extends 'base.html' %}
{% block style %}
{% endblock %}

{% block content %}
<div class ="problem-type-container">
    <p class="exercise_title">Choose the field you want to do</p>
    <form action="{% url 'exercises:problem_type' %}" method="post">
        {% csrf_token %}
        <div class="problem-type-main">
            <div class="type-problem">
                <img src="/static/img/input-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="input">
            </div>
            <div class="type-problem">
                <img src="/static/img/list-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="list">
            </div>
            <div class="type-problem">
                <img src="/static/img/tuple-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="tuple">
            </div>
            <div class="type-problem">
                <img src="/static/img/set-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="set">
            </div>
        </div>
        <div class="problem-type-main">
            <div class="type-problem">
                <img src="/static/img/date-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="Date">
            </div>
            <div class="type-problem">
                <img src="/static/img/string-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="string">
            </div>
            <div class="type-problem">
                <img src="/static/img/if-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="if">
            </div>
            <div class="type-problem">
                <img src="/static/img/for-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="for">
            </div>
        </div>
        <div class="problem-type-main">
            <div class="type-problem">
                <img src="/static/img/while-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="while">
            </div>
            <div class="type-problem">
                <img src="/static/img/function-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="function">
            </div>
            <div class="type-problem">
                <img src="/static/img/math-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="math">
            </div>
            <div class="type-problem">
                <img src="/static/img/os-icon.png" width="250px" height="125px">
                <input type="checkbox" name="keyword_list" value="os">
            </div>
        </div>
        <input type="submit" class="btn btn-outline-primary editor" value="editor">
    </form>
</div>
{% endblock %}