web/config/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import confirm_email
from django.contrib.auth import logout
from django.shortcuts import redirect
from exercises.api.api import UserSolvedProblemlist, UserSolvedProblemlistDetail
def logout_view(request):
    # 추가적인 로그아웃 전처리 작업이 있다면 여기에 추가

    logout(request)
    return redirect('/')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main.urls'), name='main'),
    path('exercises/', include('exercises.urls'), name='exercises'),
    path('logout/', logout_view, name='logout'),
    path('api/solved_list/', UserSolvedProblemlist.as_view(), name='problem_list'),
    path('api/solved_list/<str:username>/', UserSolvedProblemlistDetail.as_view(), name='problem_list'),
]

web/exercises/urls.py
from django.urls import path
from exercises import views

app_name = 'exercises'

urlpatterns = [
    path('', views.home, name='home'),
    path('problem_type/', views.problem_type, name='problem_type'),
    path('editor/', views.editor, name='editor'),
    path('share/', views.share, name='share'),
    path('grade/', views.grade, name='grade'),
    path('share_grade/', views.share_grade, name='share_grade'),
    path('test/', views.test_page, name='test'),
    path('about/', views.about_us, name='about'),
    path('login/', views.login, name = 'login'),
    path('mypage/', views.mypage, name='exercises'),
]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from allauth.account.views import confirm_email

urlpatterns = [
    path('', views.home),
    path('login/', views.login, name = 'login'),
]

web/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.min.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&family=Urbanist:wght@200;500&display=swap" rel="stylesheet">
    <!-- jQuery JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block style %}
    {% endblock %}
    <title>CoFriend</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        <img src="/static/img/logo.png" width="100px" height="50px">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exercises:home' %}">Exercise</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'exercises:about' %}">About us</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <a href="/exercises/mypage"><button type="button" class="btn btn-outline-primary Login">My Page</button></a>
        <span style="margin: 0 5px"></span>
      <a href="/logout"><button type="button" class="btn btn-outline-primary Login">Logout</button></a>
    {% else %}
      <a href="{% url 'exercises:login' %}"><button type="button" class="btn btn-outline-primary Login">LogIn</button></a>
      <span style="margin: 0 5px"></span>
      <button type="button" class="btn btn-outline-primary Join">Join</button>
    {% endif %}
    </div>
  </div>
</nav>

<!-- 페이지 내용 -->
{% block content %}
{% endblock %}

<footer class="footer-bar">
    <div>
        <h2 class="text-uppercase">Team Co-Friend</h2> <br/>
            <p>Team Leader : Kim Won Jong | Business License : 000-00-0000</p>
            <p>Address : Gachon University \ CS : +82 (0)0-000-0000, Fax : +82 (0)0-000-0000</p>
        </div>

    <div>
        <div> Copyright ⓒ Team Co-Friend</div>
    </div>
</footer>


</body>
</html>